# Data visualization

**Objectif:**
Ce notebook a pour objectif d'explorer le dataset des polices d'assurance accidents du travail afin de comprendre la structure des données et identifier les valeurs manquantes et anomalies

---

In [1]:
import pandas as pd
import numpy as np
import json

## 1. Chargement des données

Trois datasets sont fournis:

- Un dataset pour l'entrainement du modèle **(train.csv)**

- Un autre pour tester notre modèle **(test.csv)**

- Un dernier qui sert d'exemple d'output attendu **(sample_submission.csv)**

In [5]:
df_sample_submission = pd.read_csv("../data/sample_submission.csv")
df_train = pd.read_csv("../data/train.csv")
df_test = pd.read_csv("../data/test.csv")

Regardons le début de chacun des trois datasets

***Train***

In [7]:
df_train.head()

,ClaimNumber,DateTimeOfAccident,DateReported,Age,Gender,MaritalStatus,DependentChildren,DependentsOther,WeeklyWages,PartTimeFullTime,HoursWorkedPerWeek,DaysWorkedPerWeek,ClaimDescription,InitialIncurredCalimsCost,UltimateIncurredClaimCost
0,WC8285054,2002-04-09T07:00:00Z,2002-07-05T00:00:00Z,48,M,M,0,0,500.00,F,38.0,5,LIFTING TYRE INJURY TO RIGHT ARM AND WRIST INJURY,1500,4748.203388
1,WC6982224,1999-01-07T11:00:00Z,1999-01-20T00:00:00Z,43,F,M,0,0,509.34,F,37.5,5,STEPPED AROUND CRATES AND TRUCK TRAY FRACTURE ...,5500,6326.285819
2,WC5481426,1996-03-25T00:00:00Z,1996-04-14T00:00:00Z,30,M,U,0,0,709.10,F,38.0,5,CUT ON SHARP EDGE CUT LEFT THUMB,1700,2293.949087
3,WC9775968,2005-06-22T13:00:00Z,2005-07-22T00:00:00Z,41,M,S,0,0,555.46,F,38.0,5,DIGGING LOWER BACK LOWER BACK STRAIN,15000,17786.487170
4,WC2634037,1990-08-29T08:00:00Z,1990-09-27T00:00:00Z,36,M,M,0,0,377.10,F,38.0,5,REACHING ABOVE SHOULDER LEVEL ACUTE MUSCLE STR...,2800,4014.002925

Comme attendu, le dataset train contient une liste d'accidents, avec pour chaque accident différents facteurs. On retrouve bien les paramètres évoqués sur la page Kaggle qui sont les suivants:

***ClaimNumber***: Unique policy identifier

***DateTimeOfAccident***: Date and time of accident

***DateReported***: Date that accident was reported

***Age***: Age of worker

***Gender***: Gender of worker

***MaritalStatus***: Martial status of worker. (M)arried, (S)ingle, (U)nknown.

***DependentChildren***: The number of dependent children

***DependentsOther***: The number of dependants excluding children

***WeeklyWages***: Total weekly wage

***PartTimeFullTime***: Binary (P) or (F)

***HoursWorkedPerWeek***: Total hours worked per week

***DaysWorkedPerWeek***: Number of days worked per week

***ClaimDescription***: Free text description of the claim

***InitialIncurredClaimCost***: Initial estimate by the insurer of the claim cost

***UltimateIncurredClaimCost***: Total claims payments by the insurance company. This is the field you are asked to predict in the test set.

***Test***

In [8]:
df_test.head()

,ClaimNumber,DateTimeOfAccident,DateReported,Age,Gender,MaritalStatus,DependentChildren,DependentsOther,WeeklyWages,PartTimeFullTime,HoursWorkedPerWeek,DaysWorkedPerWeek,ClaimDescription,InitialIncurredCalimsCost
0,WC8145235,2002-04-02T10:00:00Z,2002-05-07T00:00:00Z,26,M,S,1,0,600.18,F,40.0,5,CAUGHT RIGHT HAND WITH HAMMER BURN TO RIGHT HAND,5300
1,WC2005111,1988-04-06T16:00:00Z,1988-04-15T00:00:00Z,31,M,M,0,0,311.54,F,35.0,5,SPRAINED RIGHT ANKLE FRACTURE RIGHT ELBOW,2000
2,WC6899143,1999-03-08T09:00:00Z,1999-04-04T00:00:00Z,57,M,M,0,0,1000.00,F,38.0,5,STRUCK HAMMER CRUSH INJURY FINGERS HAND,20000
3,WC5502023,1996-07-26T09:00:00Z,1996-09-04T00:00:00Z,33,M,M,0,0,200.00,F,38.0,5,STRUCK AGAINST AIR HOSE STRUCK GLASS LACERATIO...,350
4,WC4785156,1994-04-13T14:00:00Z,1994-07-07T00:00:00Z,32,F,M,0,0,359.60,F,40.0,5,FOREIGN BODY IN RIGHT FOOT BRUISED RIGHT BIG TOE,3000

***Sample submission***

In [10]:
df_sample_submission.head()

  ClaimNumber  UltimateIncurredClaimCost
0   WC8145235                3226.599525
1   WC2005111                 427.887042
2   WC6899143                 548.294914
3   WC5502023                 992.002064
4   WC4785156               18069.460460

Regardons les formes des datasets train et test, normalement, il devrait y avoir une colonne de moins dans le dataset test (car la colonne UltimateIncurredClaimCost est manquante étant donné que c'est notre target)

In [12]:
df_train.shape

(54000, 15)

In [13]:
df_test.shape

(36000, 14)